[package]
name = "leptos-leaflet-hotline"
description = "leptos leaflet polyline components with color gradients"
version = "0.1.0"
authors = ["Eric Krall"]
edition = "2021"
rust-version = "1.88"
repository = "https://github.com/ekrall1/leptos-leaflet-hotline"
readme = "README.md"
license = "MIT"
keywords = ["leptos", "leaflet", "leptos-leaflet", "hotline", "interactive-maps"]
categories = ["development", "development::plugins", "interactive-maps::plugins"]

[features]
default = []
csr = ["leptos/csr", "leptos-leaflet/csr"]
hydrate = ["leptos/hydrate", "leptos-leaflet/hydrate"]
ssr = ["leptos/ssr", "leptos-leaflet/ssr"]

[dependencies]
leptos = { version = "0.8.20", default-features = false }
leptos-leaflet = { version = "0.10.2", default-features = false }
js-sys = "0.3"
wasm-bindgen = "0.2"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
csscolorparser = "0.8.3"

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = { version = "0.3", features = [
    "CanvasGradient",
    "CanvasRenderingContext2d",
    "Document",
    "HtmlCanvasElement",
    "ImageData",
    "Window",
] }
